development:
  adapter: postgresql
  database: allapp_development
  username: pg_user
  password: postgres
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: allapp_test
  username: pg_user
  password: postgres
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: allapp_pro
  username: pg_user
  password: postgres
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
