# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa88f4d61957e906673e5dee9c18b85c2c260e517cc31879ff640af2f3659b0e296dc2068b85b973c7a981076378087e1e9a35d0941105085716e70749bf0140

test:
  secret_key_base: 75c2ce7c3d9583970eae1c1b8f0d05b504d63cf58c8fd2d0030218aeee61f07d0bb277736b8db9ff6f67ffa47aa24def92da92ce3bc6a67c16e15138e86c7047

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
